/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Bill Model — Immutable record of every completed payment transaction.
 * Bills are never modified after creation (append-only ledger).
 * Historical snapshots (priceAtSale, itemName) are stored in BillItem collection.
 * This schema maps to one PostgreSQL table for future migration.
 */

import mongoose, { Schema, Document } from 'mongoose';

export interface IBill extends Document {
  /**
   * Idempotency key (Phase 1.10) — stable per-checkout identifier generated by
   * the POS terminal (its local bill id). The backend dedupes on
   * { restaurantId, clientRef } so an offline queue replay can never create a
   * duplicate bill, double-deduct stock, or double-award loyalty points.
   */
  clientRef?: string;
  invoiceNumber: string;
  ticketNumber: string;
  date: string;
  time: string;
  cashierName: string;
  cashierRole: string;
  subtotal: number;
  discount: number;
  gst: number;
  grandTotal: number;
  paymentMethod: 'Cash' | 'UPI' | 'Card' | 'Wallet' | 'Split';
  splitDetails?: {
    cashAmount: number;
    cardAmount: number;
    upiAmount: number;
    walletAmount: number;
  };
  orderType: string;
  restaurantId?: mongoose.Types.ObjectId;
  branchId?: mongoose.Types.ObjectId;
  /** Source Order this bill settles (online ordering adjustments need it). */
  orderId?: mongoose.Types.ObjectId | null;
  /** Loyalty customer reference (Phase 1.6) — phone snapshot kept for historical integrity */
  customerId?: mongoose.Types.ObjectId;
  customerPhone?: string;
  customerName?: string;
  pointsEarned: number;
  pointsRedeemed: number;
  redeemedRewardTitle?: string;
  milestoneRewardAwarded?: string;
  /**
   * Receipt QR capability — opaque token baked into the printed receipt QR.
   * Resolves (via the public-store receipt endpoint) to a SANITIZED bill
   * summary: reward earned + today's line items only. NEVER exposes customer
   * name / phone / cashier PII. Expires 12h after minting so a scanned receipt
   * link can't linger forever.
   */
  receiptToken?: string;
  receiptTokenExpiresAt?: Date;
  /** Full scannable URL ({qrBaseUrl}/#/r/{receiptToken}) baked at mint time. */
  receiptUrl?: string;
  isVoided: boolean;
  voidReason?: string;
  voidedAt?: Date;
  voidedBy?: string;
  isRefunded: boolean;
  refundedAt?: Date;
  refundedBy?: string;
  refundReason?: string;
  refundAmount: number;
  refundedItems?: Array<{
    menuItemId?: string;
    itemName: string;
    quantity: number;
    amount: number;
  }>;
  createdAt: Date;
  updatedAt: Date;
}

const BillSchema = new Schema<IBill>(
  {
    clientRef: { type: String, trim: true, maxlength: 80 },
    invoiceNumber: { type: String, required: true, trim: true, index: true },
    ticketNumber: { type: String, required: true, trim: true },
    date: { type: String, required: true, trim: true, index: true },
    time: { type: String, required: true, trim: true },
    cashierName: { type: String, required: true, trim: true },
    cashierRole: { type: String, required: true, trim: true },
    subtotal: { type: Number, required: true, min: 0 },
    discount: { type: Number, default: 0, min: 0 },
    gst: { type: Number, default: 0, min: 0 },
    grandTotal: { type: Number, required: true, min: 0 },
    paymentMethod: { type: String, required: true, enum: ['Cash', 'UPI', 'Card', 'Wallet', 'Split'] },
    splitDetails: {
      type: new Schema({
        cashAmount: { type: Number, default: 0, min: 0 },
        cardAmount: { type: Number, default: 0, min: 0 },
        upiAmount: { type: Number, default: 0, min: 0 },
        walletAmount: { type: Number, default: 0, min: 0 },
      }, { _id: false }),
      default: undefined,
    },
    orderType: { type: String, required: true, trim: true },
    restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', default: null, index: true },
    branchId: { type: Schema.Types.ObjectId, ref: 'Branch', default: null, index: true },
    orderId: { type: Schema.Types.ObjectId, ref: 'Order', default: null, index: true },
    customerId: { type: Schema.Types.ObjectId, ref: 'Customer', default: null, index: true },
    customerPhone: { type: String, trim: true },
    customerName: { type: String, trim: true },
    pointsEarned: { type: Number, default: 0, min: 0 },
    pointsRedeemed: { type: Number, default: 0, min: 0 },
    redeemedRewardTitle: { type: String, trim: true },
    milestoneRewardAwarded: { type: String, trim: true },
    receiptToken: { type: String, trim: true, index: true },
    receiptTokenExpiresAt: { type: Date, default: null },
    receiptUrl: { type: String, trim: true },
    isVoided: { type: Boolean, default: false },
    voidReason: { type: String, trim: true },
    voidedAt: { type: Date, default: null },
    voidedBy: { type: String, trim: true },
    isRefunded: { type: Boolean, default: false },
    refundedAt: { type: Date, default: null },
    refundedBy: { type: String, trim: true },
    refundReason: { type: String, trim: true },
    refundAmount: { type: Number, default: 0, min: 0 },
    refundedItems: {
      type: [new Schema({
        menuItemId: { type: String, trim: true },
        itemName: { type: String, trim: true },
        quantity: { type: Number, default: 0, min: 0 },
        amount: { type: Number, default: 0, min: 0 },
      }, { _id: false })],
      default: undefined,
    },
  },
  { timestamps: true }
);

// Phase 1.10 — offline-replay idempotency. Partial: only bills that carry a
// non-null string clientRef participate in the unique constraint, so legacy or
// non-POS-created bills (no clientRef) are never rejected. Unique per
// restaurant so a bill generated on one terminal can never collide with
// another restaurant's replay. A partialFilterExpression is required here
// because Mongo `sparse` still indexes fields explicitly stored as `null`
// (which would make all clientRef-less bills in a restaurant collide).
BillSchema.index(
  { restaurantId: 1, clientRef: 1 },
  { unique: true, partialFilterExpression: { clientRef: { $type: 'string' } } }
);

BillSchema.index({ date: -1, createdAt: -1 });
BillSchema.index({ branchId: 1, date: -1 });
BillSchema.index({ branchId: 1, createdAt: -1 });
BillSchema.index({ restaurantId: 1, date: -1 });
BillSchema.index({ customerId: 1, date: -1 });
BillSchema.index({ paymentMethod: 1 });
BillSchema.index({ customerPhone: 1 });
BillSchema.index({ cashierName: 1, date: -1 });

export default mongoose.model<IBill>('Bill', BillSchema);
