/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Customer Segment Model — Dynamic customer groups based on purchase behavior.
 * Segments are updated automatically by the SegmentEngine.
 */

import mongoose, { Schema, Document } from 'mongoose';

export type SegmentType =
  | 'visit_today' | 'visit_this_week' | 'visit_this_month'
  | 'new_customer' | 'returning_customer' | 'frequent_customer'
  | 'vip_customer' | 'high_spending' | 'low_spending'
  | 'dormant_7d' | 'dormant_15d' | 'dormant_30d' | 'dormant_45d' | 'dormant_60d' | 'dormant_90d'
  | 'birthday_today' | 'birthday_tomorrow' | 'birthday_this_week'
  | 'anniversary'
  | 'weekend_customer' | 'lunch_customer' | 'dinner_customer'
  | 'tea_lover' | 'coffee_lover' | 'burger_lover' | 'pizza_lover' | 'dessert_lover'
  | 'vegetarian'
  | 'family_orders' | 'large_orders' | 'online_orders'
  | 'cash_customer' | 'upi_customer' | 'card_customer'
  | 'loyalty_member' | 'reward_redeemer'
  | 'custom';

export interface ICustomerSegment extends Document {
  restaurantId: mongoose.Types.ObjectId;
  name: string;
  type: SegmentType;
  description: string;
  /** Customer IDs (phone numbers) that belong to this segment */
  customerPhones: string[];
  /** Customer count (updated daily) */
  customerCount: number;
  /** Average spend of customers in this segment */
  averageSpend: number;
  /** Average visit frequency (days between visits) */
  averageVisitFrequency: number;
  /** Last campaign sent to this segment */
  lastCampaignDate?: string;
  /** Whether this segment is auto-generated (vs custom) */
  isAutoGenerated: boolean;
  /** Custom filter rules (JSON string for custom segments) */
  filterRules?: string;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const CustomerSegmentSchema = new Schema<ICustomerSegment>(
  {
    restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true, index: true },
    name: { type: String, required: true, trim: true },
    type: { type: String, enum: [
      'visit_today', 'visit_this_week', 'visit_this_month',
      'new_customer', 'returning_customer', 'frequent_customer',
      'vip_customer', 'high_spending', 'low_spending',
      'dormant_7d', 'dormant_15d', 'dormant_30d', 'dormant_45d', 'dormant_60d', 'dormant_90d',
      'birthday_today', 'birthday_tomorrow', 'birthday_this_week',
      'anniversary',
      'weekend_customer', 'lunch_customer', 'dinner_customer',
      'tea_lover', 'coffee_lover', 'burger_lover', 'pizza_lover', 'dessert_lover',
      'vegetarian',
      'family_orders', 'large_orders', 'online_orders',
      'cash_customer', 'upi_customer', 'card_customer',
      'loyalty_member', 'reward_redeemer',
      'custom',
    ], required: true },
    description: { type: String, default: '', trim: true },
    customerPhones: [{ type: String, trim: true }],
    customerCount: { type: Number, default: 0, min: 0 },
    averageSpend: { type: Number, default: 0, min: 0 },
    averageVisitFrequency: { type: Number, default: 0, min: 0 },
    lastCampaignDate: { type: String, trim: true },
    isAutoGenerated: { type: Boolean, default: true },
    filterRules: { type: String, trim: true },
    isDeleted: { type: Boolean, default: false },
  },
  { timestamps: true }
);

CustomerSegmentSchema.index({ restaurantId: 1, type: 1 });
CustomerSegmentSchema.index({ restaurantId: 1, customerCount: -1 });

export default mongoose.model<ICustomerSegment>('CustomerSegment', CustomerSegmentSchema);
