/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * ReportsController — Phase 1.8 report endpoints.
 *
 * Every handler resolves the tenant from the authenticated user, builds a
 * ReportScope (restaurantId + optional branchId from the employee profile),
 * delegates to the report services, and returns already-computed data.
 * Exports stream CSV / produce XLSX / PDF from the exact same data.
 */

import { Request, Response } from 'express';
import {
  salesReportService, productReportService, inventoryReportService,
  employeeReportService, closingReportService, branchReportService, summaryService,
} from '../services';
import { exportService, ExportMeta, ExportTable } from '../services/exportService';
import type { ReportScope, ReportUser } from '../types';

function userOf(req: Request): ReportUser {
  const u = (req as any).user as ReportUser | undefined;
  return u || { restaurantId: '' };
}

function scopeOf(req: Request): ReportScope {
  const user = userOf(req);
  const q = req.query as Record<string, string | undefined>;
  return {
    restaurantId: user.restaurantId,
    branchId: q.branchId || user.branchId,
    startDate: q.startDate,
    endDate: q.endDate,
    openingTime: q.openingTime,
  };
}

function ok(res: Response, data: unknown): void {
  res.json({ data });
}

/** Build shared export meta from the request scope. */
function exportMeta(req: Request, title: string, scope: ReportScope): ExportMeta {
  const user = userOf(req);
  return {
    title,
    generatedAt: new Date().toISOString(),
    filters: {
      'Date Range': `${scope.startDate || 'all'} → ${scope.endDate || 'all'}`,
      Restaurant: user.restaurantId || '—',
      Branch: scope.branchId || 'All',
    },
    footer: 'Generated by POS Reports Engine',
  };
}

function extractTable(payload: any): ExportTable {
  if (Array.isArray(payload)) {
    const headers = payload.length ? Object.keys(payload[0]) : ['Value'];
    return { headers, rows: payload.map((r) => headers.map((h) => r[h] ?? '')) };
  }
  const keys = Object.keys(payload || {});
  return {
    headers: ['Key', 'Value'],
    rows: keys.map((k) => [k, typeof payload[k] === 'object' ? JSON.stringify(payload[k]) : String(payload[k] ?? '')]),
  };
}

// ─── Sales ───────────────────────────────────────────────────────

export async function salesSummary(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.summary(scopeOf(req)));
}
export async function salesTrend(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.trend(scopeOf(req)));
}
export async function salesHourly(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.hourly(scopeOf(req)));
}
export async function salesPeakHours(req: Request, res: Response): Promise<void> {
  const scope = scopeOf(req);
  const hourly = await salesReportService.hourly(scope);
  const sorted = [...hourly].sort((a, b) => b.orders - a.orders);
  ok(res, { hourly, peakHour: sorted[0] || null });
}
export async function salesPayments(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.payments(scopeOf(req)));
}
export async function salesOrderTypes(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.orderTypes(scopeOf(req)));
}
export async function salesCashiers(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.cashiers(scopeOf(req)));
}
export async function salesPeriods(req: Request, res: Response): Promise<void> {
  ok(res, await salesReportService.periods(scopeOf(req)));
}
export async function salesTopDays(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 10;
  ok(res, await salesReportService.topDays(scopeOf(req), limit));
}
export async function salesTopHours(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 10;
  ok(res, await salesReportService.topHours(scopeOf(req), limit));
}

// ─── Products ────────────────────────────────────────────────────

export async function productTop(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 10;
  ok(res, await productReportService.top(scopeOf(req), limit));
}
export async function productLeast(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 10;
  ok(res, await productReportService.least(scopeOf(req), limit));
}
export async function productRevenue(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 10;
  ok(res, await productReportService.revenue(scopeOf(req), limit));
}
export async function productConfigBreakdown(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 100;
  ok(res, await productReportService.configBreakdown(scopeOf(req), limit));
}
export async function productCategories(req: Request, res: Response): Promise<void> {
  ok(res, await productReportService.categories(scopeOf(req)));
}
export async function productMenuEngineering(req: Request, res: Response): Promise<void> {
  ok(res, await productReportService.menuEngineering(scopeOf(req)));
}
export async function productAbc(req: Request, res: Response): Promise<void> {
  ok(res, await productReportService.abc(scopeOf(req)));
}
export async function productInactive(req: Request, res: Response): Promise<void> {
  ok(res, await productReportService.inactive(scopeOf(req)));
}
export async function productDeleted(req: Request, res: Response): Promise<void> {
  ok(res, await productReportService.deleted(scopeOf(req)));
}

// ─── Inventory ───────────────────────────────────────────────────

export async function inventoryStock(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.stock(scopeOf(req)));
}
export async function inventoryLowStock(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.lowStock(scopeOf(req)));
}
export async function inventoryValuation(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.valuation(scopeOf(req)));
}
export async function inventoryMovement(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.movement(scopeOf(req)));
}
export async function inventoryAging(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.aging(scopeOf(req)));
}
export async function inventoryReorder(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.reorder(scopeOf(req)));
}
export async function inventoryFastSlow(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.fastSlow(scopeOf(req)));
}
export async function inventoryWaste(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.waste(scopeOf(req)));
}
export async function inventorySummary(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.summary(scopeOf(req)));
}
export async function inventoryExpiry(req: Request, res: Response): Promise<void> {
  const days = Number(req.query.days) || 30;
  ok(res, await inventoryReportService.expiry(scopeOf(req), days));
}
export async function inventorySuppliers(req: Request, res: Response): Promise<void> {
  ok(res, await inventoryReportService.suppliers(scopeOf(req)));
}

// ─── Employees ───────────────────────────────────────────────────

export async function employeePerformance(req: Request, res: Response): Promise<void> {
  ok(res, await employeeReportService.performance(scopeOf(req)));
}
export async function employeeAuditActivity(req: Request, res: Response): Promise<void> {
  const limit = Number(req.query.limit) || 100;
  ok(res, await employeeReportService.auditActivity(scopeOf(req), limit));
}

// ─── Branches (consolidated per-branch summary) ───────────────────

export async function branchSummary(req: Request, res: Response): Promise<void> {
  ok(res, await branchReportService.branchSummary(scopeOf(req)));
}

// ─── Closing (Owner/Manager only) ────────────────────────────────

export async function closingX(req: Request, res: Response): Promise<void> {
  const scope = scopeOf(req);
  ok(res, await closingReportService.xReport(scope, req.query.date as string));
}
export async function closingZ(req: Request, res: Response): Promise<void> {
  const scope = scopeOf(req);
  ok(res, await closingReportService.zReport(scope, req.query.date as string));
}

// ─── Summaries ───────────────────────────────────────────────────

export async function summariesDaily(req: Request, res: Response): Promise<void> {
  ok(res, await summaryService.daily(scopeOf(req)));
}
export async function summariesMonthly(req: Request, res: Response): Promise<void> {
  ok(res, await summaryService.monthly(scopeOf(req)));
}
export async function summariesYearly(req: Request, res: Response): Promise<void> {
  ok(res, await summaryService.yearly(scopeOf(req)));
}
export async function summariesRebuild(req: Request, res: Response): Promise<void> {
  ok(res, await summaryService.rebuild(scopeOf(req)));
}

// ─── Exports (Owner/Manager only) ────────────────────────────────

export async function exportReport(req: Request, res: Response): Promise<void> {
  const scope = scopeOf(req);
  const format = (req.query.format as 'csv' | 'xlsx' | 'pdf') || 'csv';
  const report = req.query.report as string;
  const title = `Report - ${report}`;

  let payload: unknown;
  switch (report) {
    case 'sales': payload = await salesReportService.summary(scope); break;
    case 'products': payload = await productReportService.top(scope, 100); break;
    case 'inventory': payload = await inventoryReportService.stock(scope); break;
    case 'employees': payload = await employeeReportService.performance(scope); break;
    case 'payments': payload = await salesReportService.payments(scope); break;
    case 'categories': payload = await productReportService.categories(scope); break;
    case 'branch': payload = await branchReportService.branchSummary(scope); break;
    default: res.status(400).json({ error: `Unknown report: ${report}` }); return;
  }

  const table = extractTable(payload);
  const meta = exportMeta(req, title, scope);
  const headers = exportService.exportHeaders(format, title);
  res.set(headers);

  if (format === 'csv') {
    const stream = exportService.streamCsv(table, meta);
    stream.pipe(res);
    return;
  }
  if (format === 'xlsx') {
    res.send(await exportService.buildXlsx(table, meta));
    return;
  }
  res.send(await exportService.buildPdf(table, meta));
}
