/**
 * =============================================================================
 *  analyticsService.ts — Platform Analytics Aggregation Service (Phase 2.6)
 * =============================================================================
 *
 * Purpose:
 *   Central service for all admin dashboard analytics aggregation.
 *   Uses MongoDB aggregation pipelines for performance and accuracy.
 *
 * Principles:
 *   - All aggregation happens on the database side
 *   - No loading large datasets into memory
 *   - No frontend reduce/calculate logic
 *   - Every metric is generated by backend aggregation
 *   - Reuses existing models and architecture
 */

import mongoose from 'mongoose';
import Restaurant from '../models/Restaurant';
import User from '../models/User';
import Device from '../models/Device';
import Subscription, { SubscriptionStatus } from '../models/Subscription';

// NOTE: 'cancelled'/'expired' are NOT valid SubscriptionStatus values (schema
// enum: trial | active | grace | suspended). This churn metric therefore
// currently always reads 0. Flagged for owner review — the cast below only
// makes the filter typecheck; it does not change runtime behavior.
import AuditLog from '../models/AuditLog';
import AIUsageLog from '../models/AIUsageLog';
import VoiceAuditLog from '../modules/voice-inventory/models/VoiceAuditLog';
import Payment from '../models/Payment';

// ─── Types ─────────────────────────────────────────────────────

export interface DashboardStats {
  totalRestaurants: number;
  activeRestaurants: number;
  inactiveRestaurants: number;
  suspendedRestaurants: number;
  totalOwners: number;
  activeOwners: number;
  totalDevices: number;
  activeDevices: number;
  offlineDevices: number;
  pendingDevices: number;
  blockedDevices: number;
  subscriptionsExpiring: number;
  todayLogins: number;
  aiRequests: number;
  aiSuccessRate: number;
  totalOrders: number;
  totalBills: number;
  totalApiRequests: number;
  subscriptionCounts: {
    total: number;
    active: number;
    paused: number;
    expired: number;
    trial: number;
    cancelled: number;
    suspended: number;
  };
}

export interface ChartDataPoint {
  name: string;
  value: number;
}

export interface AnalyticsData {
  restaurantGrowth: ChartDataPoint[];
  dailyLogins: ChartDataPoint[];
  dailyActiveRestaurants: ChartDataPoint[];
  subscriptions: ChartDataPoint[];
  aiUsage: ChartDataPoint[];
  aiUsageByFeature: { name: string; value: number }[];
  mostActiveRestaurants: { name: string; value: number }[];
  deviceTrends: ChartDataPoint[];
  revenueDaily: ChartDataPoint[];
  revenueWeekly: ChartDataPoint[];
  revenueMonthly: ChartDataPoint[];
  revenueYearly: ChartDataPoint[];
  growthDaily: ChartDataPoint[];
  growthWeekly: ChartDataPoint[];
  growthMonthly: ChartDataPoint[];
  growthYearly: ChartDataPoint[];
  apiRequestsDaily: ChartDataPoint[];
}

export interface AIAnalytics {
  totalRequests: number;
  successRate: number;
  failures: number;
  fallbackUsage: number;
  cacheHits: number;
  averageLatency: number;
  byFeature: { name: string; value: number; successRate: number }[];
  byRestaurant: { name: string; value: number }[];
  dailyTrend: ChartDataPoint[];
}

export interface DeviceAnalytics {
  total: number;
  active: number;
  inactive: number;
  blocked: number;
  pending: number;
  rejected: number;
  online: number;
  offline: number;
  health: { healthy: number; unhealthy: number; unknown: number };
  byPlatform: { name: string; value: number }[];
  byStatus: { name: string; value: number }[];
  trends: ChartDataPoint[];
}

export interface GrowthMetrics {
  restaurantGrowth: { daily: number; weekly: number; monthly: number; yearly: number };
  revenueGrowth: { daily: number; weekly: number; monthly: number; yearly: number };
  userGrowth: { daily: number; weekly: number; monthly: number; yearly: number };
  deviceGrowth: { daily: number; weekly: number; monthly: number; yearly: number };
  aiUsageGrowth: { daily: number; weekly: number; monthly: number; yearly: number };
}

export interface ChurnMetrics {
  suspendedRestaurants: number;
  subscriptionChurn: { total: number; rate: number };
  trialConversions: { total: number; converted: number; rate: number };
  failedRenewals: number;
  inactiveRestaurants: number;
  churnRate: number;
  churnByMonth: ChartDataPoint[];
}

export interface ActivityMetrics {
  dailyLogins: number;
  weeklyLogins: number;
  monthlyLogins: number;
  activeUsers: number;
  activeOwners: number;
  recentActivity: number;
  ownerActivity: { daily: number; weekly: number; monthly: number };
  deviceActivity: { daily: number; weekly: number; monthly: number };
  aiActivity: { daily: number; weekly: number; monthly: number };
}

export interface RevenueMetrics {
  total: { revenue: number; count: number };
  cash: { revenue: number; count: number; percentage: number };
  razorpay: { revenue: number; count: number; percentage: number };
  monthly: Array<{ month: string; cash: number; razorpay: number; cashCount: number; razorpayCount: number; total: number }>;
  daily: Array<{ date: string; cash: number; razorpay: number; total: number }>;
  weekly: Array<{ week: string; cash: number; razorpay: number; total: number }>;
  yearly: Array<{ year: string; cash: number; razorpay: number; total: number }>;
  byPaymentMethod: { name: string; value: number }[];
  recent: Array<{ id: string; invoiceNumber: string; amount: number; gateway: string; paymentMethod: string; createdAt: string }>;
}

export interface ApiRequestAnalytics {
  totalRequests: number;
  requestsPerEndpoint: { endpoint: string; count: number }[];
  successRate: number;
  errorRate: number;
  averageLatency: number;
  slowEndpoints: { endpoint: string; averageLatency: number; count: number }[];
  daily: ChartDataPoint[];
}

// ─── Helper Functions ─────────────────────────────────────────

function getDateRanges() {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1000);
  const thisWeek = new Date(today.getTime() - today.getDay() * 24 * 60 * 60 * 1000);
  const lastWeek = new Date(thisWeek.getTime() - 7 * 24 * 60 * 60 * 1000);
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1);
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
  const thisYear = new Date(today.getFullYear(), 0, 1);
  const lastYear = new Date(today.getFullYear() - 1, 0, 1);
  const thirtyDaysAgo = new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000);
  const oneYearAgo = new Date(today.getTime() - 365 * 24 * 60 * 60 * 1000);
  return { now, today, yesterday, thisWeek, lastWeek, thisMonth, lastMonth, thisYear, lastYear, thirtyDaysAgo, oneYearAgo };
}

function getDaysArray(days: number): string[] {
  const today = new Date();
  return Array.from({ length: days }, (_, i) => {
    const d = new Date(today.getTime() - (days - 1 - i) * 24 * 60 * 60 * 1000);
    return d.toISOString().substring(0, 10);
  });
}

async function getCollectionCount(modelName: string, filter: Record<string, any> = {}): Promise<number> {
  try {
    const model = mongoose.model(modelName);
    return await model.countDocuments(filter).exec();
  } catch {
    return 0;
  }
}

function calcGrowth(current: number, previous: number): number {
  if (previous === 0) return current > 0 ? 100 : 0;
  return Math.round(((current - previous) / previous) * 100);
}

// ─── Dashboard Stats ──────────────────────────────────────────

export async function getDashboardStats(): Promise<DashboardStats> {
  const { today, thirtyDaysAgo } = getDateRanges();

  const [
    totalRestaurants,
    activeRestaurants,
    suspendedRestaurants,
    totalOwners,
    activeOwners,
    totalDevices,
    activeDevices,
    offlineDevices,
    pendingDevices,
    blockedDevices,
    subscriptionsExpiring,
    todayLogins,
    totalOrders,
    totalBillsResult,
  ] = await Promise.all([
    Restaurant.countDocuments({ isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ isActive: true, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ isActive: false, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', isActive: true, isDeleted: { $ne: true } }).exec(),
    Device.countDocuments({ isDeleted: false }).exec(),
    Device.countDocuments({ status: 'active', isDeleted: false }).exec(),
    Device.countDocuments({
      $or: [{ isOnline: false }, { lastHeartbeatAt: { $lt: new Date(Date.now() - 15 * 60 * 1000) } }],
      isDeleted: false,
    }).exec(),
    Device.countDocuments({ status: 'pending', isDeleted: false }).exec(),
    Device.countDocuments({ status: 'blocked', isDeleted: false }).exec(),
    Subscription.countDocuments({
      endDate: { $gte: today, $lte: new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000) },
    }).exec(),
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: today } }).exec(),
    getCollectionCount('Order', { createdAt: { $gte: thirtyDaysAgo } }),
    getCollectionCount('Bill', { createdAt: { $gte: thirtyDaysAgo } }),
  ]);

  // Subscription counts via aggregation (accurate, no type casting)
  const subscriptionCounts = await Subscription.aggregate([
    { $group: { _id: '$status', count: { $sum: 1 } } },
  ]).exec();

  const statusMap: Record<string, number> = { active: 0, paused: 0, expired: 0, trial: 0, cancelled: 0, suspended: 0 };
  subscriptionCounts.forEach((row: { _id: string; count: number }) => {
    const status = (row._id || 'unknown').toLowerCase();
    if (status in statusMap) statusMap[status] = row.count;
  });

  const totalSubscriptions = subscriptionCounts.reduce((sum: number, r: { count: number }) => sum + r.count, 0);

  // AI requests
  const [aiModuleRequests, voiceAiRequests] = await Promise.all([
    AIUsageLog.countDocuments({}).exec(),
    VoiceAuditLog.countDocuments({ source: { $in: ['voice', 'ai_suggested'] } }).exec(),
  ]);

  const aiStats = await AIUsageLog.aggregate([
    { $match: { createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: null, total: { $sum: 1 }, successes: { $sum: { $cond: ['$success', 1, 0] } } } },
  ]).exec();

  const aiSuccessRate = aiStats[0]?.total > 0 ? Math.round((aiStats[0].successes / aiStats[0].total) * 100) : 0;
  const totalApiRequests = await AuditLog.countDocuments({ createdAt: { $gte: thirtyDaysAgo } }).exec();

  return {
    totalRestaurants,
    activeRestaurants,
    inactiveRestaurants: totalRestaurants - activeRestaurants,
    suspendedRestaurants,
    totalOwners,
    activeOwners,
    totalDevices,
    activeDevices,
    offlineDevices,
    pendingDevices,
    blockedDevices,
    subscriptionsExpiring,
    todayLogins,
    aiRequests: aiModuleRequests + voiceAiRequests,
    aiSuccessRate,
    totalOrders,
    totalBills: totalBillsResult,
    totalApiRequests,
    subscriptionCounts: {
      total: totalSubscriptions,
      active: statusMap.active,
      paused: statusMap.paused,
      expired: statusMap.expired,
      trial: statusMap.trial,
      cancelled: statusMap.cancelled,
      suspended: statusMap.suspended,
    },
  };
}

// ─── Analytics Data (Charts) ──────────────────────────────────

export async function getAnalyticsData(): Promise<AnalyticsData> {
  const { thirtyDaysAgo, oneYearAgo } = getDateRanges();
  const days = getDaysArray(30);
  const months = Array.from({ length: 12 }, (_, i) => {
    const d = new Date(); d.setMonth(d.getMonth() - 11 + i);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  });
  const years = Array.from({ length: 5 }, (_, i) => String(new Date().getFullYear() - 4 + i));

  // ─── Daily logins ──────────────────────────────────────────
  const loginAgg = await AuditLog.aggregate([
    { $match: { action: { $regex: /LOGIN|login/i }, createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const loginMap = new Map(loginAgg.map((r: any) => [r._id, r.count]));
  const dailyLogins = days.map((d) => ({ name: d, value: loginMap.get(d) || 0 }));

  // ─── Restaurant growth ─────────────────────────────────────
  const restGrowthAgg = await Restaurant.aggregate([
    { $match: { createdAt: { $gte: thirtyDaysAgo }, isDeleted: { $ne: true } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const rgMap = new Map(restGrowthAgg.map((r: any) => [r._id, r.count]));
  const restaurantGrowth = days.map((d) => ({ name: d, value: rgMap.get(d) || 0 }));

  // ─── Daily active restaurants ──────────────────────────────
  const darAgg = await AuditLog.aggregate([
    { $match: { entityType: 'Restaurant', createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: { date: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, rid: '$restaurantId' } } },
    { $group: { _id: '$_id.date', count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const darMap = new Map(darAgg.map((r: any) => [r._id, r.count]));
  const dailyActiveRestaurants = days.map((d) => ({ name: d, value: darMap.get(d) || 0 }));

  // ─── Subscription trend ────────────────────────────────────
  const subAgg = await Subscription.aggregate([
    { $match: { createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const subMap = new Map(subAgg.map((r: any) => [r._id, r.count]));
  const subscriptions = days.map((d) => ({ name: d, value: subMap.get(d) || 0 }));

  // ─── AI usage ──────────────────────────────────────────────
  const [aiAgg, voiceAiAgg] = await Promise.all([
    AIUsageLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]).exec(),
    VoiceAuditLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo }, source: { $in: ['voice', 'ai_suggested'] } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]).exec(),
  ]);
  const aiMap = new Map(aiAgg.map((r: any) => [r._id, r.count]));
  voiceAiAgg.forEach((r: any) => aiMap.set(r._id, (aiMap.get(r._id) || 0) + r.count));
  const aiUsage = days.map((d) => ({ name: d, value: aiMap.get(d) || 0 }));

  // ─── AI usage by feature ───────────────────────────────────
  const [featAgg, voiceFeatAgg] = await Promise.all([
    AIUsageLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo } } },
      { $group: { _id: '$feature', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]).exec(),
    VoiceAuditLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo }, source: { $in: ['voice', 'ai_suggested'] } } },
      { $group: { _id: 'voice', count: { $sum: 1 } } },
    ]).exec(),
  ]);
  const featMap: Record<string, number> = {};
  featAgg.forEach((r: any) => { featMap[r._id] = (featMap[r._id] || 0) + r.count; });
  voiceFeatAgg.forEach((r: any) => { featMap[r._id] = (featMap[r._id] || 0) + r.count; });
  const aiUsageByFeature = Object.entries(featMap).sort(([, a], [, b]) => b - a).map(([name, value]) => ({ name, value }));

  // ─── Most active restaurants ───────────────────────────────
  const [activeAi, activeVoice] = await Promise.all([
    AIUsageLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo } } },
      { $group: { _id: '$restaurantId', count: { $sum: 1 } } },
      { $sort: { count: -1 } }, { $limit: 10 },
    ]).exec(),
    VoiceAuditLog.aggregate([
      { $match: { createdAt: { $gte: thirtyDaysAgo }, source: { $in: ['voice', 'ai_suggested'] } } },
      { $group: { _id: '$restaurantId', count: { $sum: 1 } } },
      { $sort: { count: -1 } }, { $limit: 10 },
    ]).exec(),
  ]);
  const usageByRid: Record<string, number> = {};
  activeAi.forEach((r: any) => { if (r._id) usageByRid[r._id.toString()] = (usageByRid[r._id.toString()] || 0) + r.count; });
  activeVoice.forEach((r: any) => { if (r._id) usageByRid[r._id.toString()] = (usageByRid[r._id.toString()] || 0) + r.count; });
  const sortedRids = Object.entries(usageByRid).sort(([, a], [, b]) => b - a).slice(0, 10).map(([id]) => id);
  const rNames = sortedRids.length > 0 ? await Restaurant.find({ _id: { $in: sortedRids } }).select('name').exec() : [];
  const nameMap = new Map(rNames.map((r) => [r._id.toString(), r.name]));
  const mostActiveRestaurants = sortedRids.map((id) => ({ name: nameMap.get(id) || 'Unknown', value: usageByRid[id] }));

  // ─── Device trends ─────────────────────────────────────────
  const devAgg = await Device.aggregate([
    { $match: { isDeleted: false } },
    { $group: { _id: null, active: { $sum: { $cond: [{ $eq: ['$status', 'active'] }, 1, 0] } }, inactive: { $sum: { $cond: [{ $eq: ['$status', 'inactive'] }, 1, 0] } }, pending: { $sum: { $cond: [{ $eq: ['$status', 'pending'] }, 1, 0] } }, blocked: { $sum: { $cond: [{ $eq: ['$status', 'blocked'] }, 1, 0] } }, rejected: { $sum: { $cond: [{ $eq: ['$status', 'rejected'] }, 1, 0] } } } },
  ]).exec();
  const ds = devAgg[0] || {};
  const deviceTrends = [
    { name: 'Active', value: ds.active || 0 },
    { name: 'Inactive', value: ds.inactive || 0 },
    { name: 'Pending', value: ds.pending || 0 },
    { name: 'Blocked', value: ds.blocked || 0 },
    { name: 'Rejected', value: ds.rejected || 0 },
  ];

  // ─── Revenue daily ─────────────────────────────────────────
  const revDailyAgg = await Payment.aggregate([
    { $match: { status: 'success', createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, cash: { $sum: { $cond: [{ $in: ['$gateway', ['cash', 'manual']] }, '$amount', 0] } }, razorpay: { $sum: { $cond: [{ $in: ['$gateway', ['razorpay', 'online']] }, '$amount', 0] } } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const revDailyMap = new Map(revDailyAgg.map((r: any) => [r._id, r.cash + r.razorpay]));
  const revenueDaily = days.map((d) => ({ name: d, value: revDailyMap.get(d) || 0 }));

  // ─── Revenue monthly ───────────────────────────────────────
  const revMonthlyAgg = await Payment.aggregate([
    { $match: { status: 'success', createdAt: { $gte: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000) } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, total: { $sum: '$amount' } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const revMonthlyMap = new Map(revMonthlyAgg.map((r: any) => [r._id, r.total]));
  const revenueMonthly = months.map((m) => ({ name: m, value: revMonthlyMap.get(m) || 0 }));

  // ─── Revenue weekly ────────────────────────────────────────
  const revWeeklyAgg = await Payment.aggregate([
    { $match: { status: 'success', createdAt: { $gte: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000) } } },
    { $group: { _id: { year: { $isoWeekYear: '$createdAt' }, week: { $isoWeek: '$createdAt' } }, total: { $sum: '$amount' } } },
    { $sort: { '_id.year': 1, '_id.week': 1 } },
  ]).exec();
  const revenueWeekly = revWeeklyAgg.map((r: any) => ({ name: `${r._id.year}-W${r._id.week}`, value: r.total }));

  // ─── Revenue yearly ────────────────────────────────────────
  const revYearlyAgg = await Payment.aggregate([
    { $match: { status: 'success' } },
    { $group: { _id: { $dateToString: { format: '%Y', date: '$createdAt' } }, total: { $sum: '$amount' } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const revYearlyMap = new Map(revYearlyAgg.map((r: any) => [r._id, r.total]));
  const revenueYearly = years.map((y) => ({ name: y, value: revYearlyMap.get(y) || 0 }));

  // ─── Growth daily/weekly/monthly/yearly ────────────────────
  const growthDailyAgg = await Restaurant.aggregate([
    { $match: { createdAt: { $gte: thirtyDaysAgo }, isDeleted: { $ne: true } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const gdMap = new Map(growthDailyAgg.map((r: any) => [r._id, r.count]));
  const growthDaily = days.map((d) => ({ name: d, value: gdMap.get(d) || 0 }));

  const growthWeeklyAgg = await Restaurant.aggregate([
    { $match: { createdAt: { $gte: oneYearAgo }, isDeleted: { $ne: true } } },
    { $group: { _id: { year: { $isoWeekYear: '$createdAt' }, week: { $isoWeek: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { '_id.year': 1, '_id.week': 1 } },
  ]).exec();
  const growthWeekly = growthWeeklyAgg.map((r: any) => ({ name: `${r._id.year}-W${r._id.week}`, value: r.count }));

  const growthMonthlyAgg = await Restaurant.aggregate([
    { $match: { isDeleted: { $ne: true } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const gmMap = new Map(growthMonthlyAgg.map((r: any) => [r._id, r.count]));
  const growthMonthly = months.map((m) => ({ name: m, value: gmMap.get(m) || 0 }));

  const growthYearlyAgg = await Restaurant.aggregate([
    { $match: { isDeleted: { $ne: true } } },
    { $group: { _id: { $dateToString: { format: '%Y', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const gyMap = new Map(growthYearlyAgg.map((r: any) => [r._id, r.count]));
  const growthYearly = years.map((y) => ({ name: y, value: gyMap.get(y) || 0 }));

  // ─── API requests daily ────────────────────────────────────
  const apiAgg = await AuditLog.aggregate([
    { $match: { createdAt: { $gte: thirtyDaysAgo } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();
  const apiMap = new Map(apiAgg.map((r: any) => [r._id, r.count]));
  const apiRequestsDaily = days.map((d) => ({ name: d, value: apiMap.get(d) || 0 }));

  return {
    restaurantGrowth, dailyLogins, dailyActiveRestaurants, subscriptions, aiUsage,
    aiUsageByFeature, mostActiveRestaurants, deviceTrends,
    revenueDaily, revenueWeekly, revenueMonthly, revenueYearly,
    growthDaily, growthWeekly, growthMonthly, growthYearly,
    apiRequestsDaily,
  };
}

// ─── AI Analytics ─────────────────────────────────────────────

export async function getAIAnalytics(days: number = 30): Promise<AIAnalytics> {
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);

  const stats = await AIUsageLog.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: null, total: { $sum: 1 }, successes: { $sum: { $cond: ['$success', 1, 0] } }, fallbacks: { $sum: { $cond: ['$fallback', 1, 0] } }, cacheHits: { $sum: { $cond: ['$cached', 1, 0] } }, totalLatency: { $sum: '$latencyMs' } } },
  ]).exec();
  const s = stats[0] || { total: 0, successes: 0, fallbacks: 0, cacheHits: 0, totalLatency: 0 };

  const voiceCount = (await VoiceAuditLog.aggregate([
    { $match: { createdAt: { $gte: since }, source: { $in: ['voice', 'ai_suggested'] } } },
    { $count: 'count' },
  ]).exec())[0]?.count || 0;

  const totalRequests = s.total + voiceCount;
  const successRate = s.total > 0 ? Math.round((s.successes / s.total) * 100) : 0;

  const byFeature = (await AIUsageLog.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: '$feature', count: { $sum: 1 }, successes: { $sum: { $cond: ['$success', 1, 0] } } } },
    { $sort: { count: -1 } },
  ]).exec()).map((r: any) => ({ name: r._id, value: r.count, successRate: r.count > 0 ? Math.round((r.successes / r.count) * 100) : 0 }));

  const byRestData = await AIUsageLog.aggregate([
    { $match: { createdAt: { $gte: since }, restaurantId: { $ne: null } } },
    { $group: { _id: '$restaurantId', count: { $sum: 1 } } },
    { $sort: { count: -1 } }, { $limit: 10 },
  ]).exec();
  const ridNames = byRestData.filter((r: any) => r._id).map((r: any) => r._id);
  const rDocs = ridNames.length > 0 ? await Restaurant.find({ _id: { $in: ridNames } }).select('name').exec() : [];
  const rnMap = new Map(rDocs.map((r) => [r._id.toString(), r.name]));
  const byRestaurant = byRestData.filter((r: any) => r._id).map((r: any) => ({ name: rnMap.get(r._id.toString()) || 'Unknown', value: r.count }));

  // Daily trend
  const [aiDaily, voiceDaily] = await Promise.all([
    AIUsageLog.aggregate([
      { $match: { createdAt: { $gte: since } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]).exec(),
    VoiceAuditLog.aggregate([
      { $match: { createdAt: { $gte: since }, source: { $in: ['voice', 'ai_suggested'] } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]).exec(),
  ]);
  const dailyMap = new Map(aiDaily.map((r: any) => [r._id, r.count]));
  voiceDaily.forEach((r: any) => dailyMap.set(r._id, (dailyMap.get(r._id) || 0) + r.count));
  const allDays = getDaysArray(days);
  const daily = allDays.map((d) => ({ name: d, value: dailyMap.get(d) || 0 }));

    const failures = s.total - s.successes;
    return {
      totalRequests,
      successRate,
      failures,
      fallbackUsage: s.fallbacks || 0,
      cacheHits: s.cacheHits || 0,
      averageLatency: s.total > 0 ? Math.round((s.totalLatency || 0) / s.total) : 0,
      byFeature,
      byRestaurant,
      dailyTrend: daily,
    };
}

// ─── Device Analytics ─────────────────────────────────────────

export async function getDeviceAnalytics(): Promise<DeviceAnalytics> {
  const [totalStats, platformStats, statusStats, heartbeatStats] = await Promise.all([
    Device.aggregate([
      { $match: { isDeleted: false } },
      { $group: { _id: null, total: { $sum: 1 }, active: { $sum: { $cond: [{ $eq: ['$status', 'active'] }, 1, 0] } }, inactive: { $sum: { $cond: [{ $eq: ['$status', 'inactive'] }, 1, 0] } }, blocked: { $sum: { $cond: [{ $eq: ['$status', 'blocked'] }, 1, 0] } }, pending: { $sum: { $cond: [{ $eq: ['$status', 'pending'] }, 1, 0] } }, rejected: { $sum: { $cond: [{ $eq: ['$status', 'rejected'] }, 1, 0] } }, online: { $sum: { $cond: ['$isOnline', 1, 0] } }, offline: { $sum: { $cond: [{ $not: '$isOnline' }, 1, 0] } } } },
    ]).exec(),
    Device.aggregate([{ $match: { isDeleted: false, platform: { $ne: null } } }, { $group: { _id: '$platform', count: { $sum: 1 } } }, { $sort: { count: -1 } }]).exec(),
    Device.aggregate([{ $match: { isDeleted: false } }, { $group: { _id: '$status', count: { $sum: 1 } } }, { $sort: { count: -1 } }]).exec(),
    Device.aggregate([
      { $match: { isDeleted: false } },
      { $group: { _id: null, healthy: { $sum: { $cond: [{ $gte: ['$lastHeartbeatAt', new Date(Date.now() - 15 * 60 * 1000)] }, 1, 0] } }, unhealthy: { $sum: { $cond: [{ $and: [{ $lt: ['$lastHeartbeatAt', new Date(Date.now() - 15 * 60 * 1000)] }, { $ne: ['$lastHeartbeatAt', null] }] }, 1, 0] } }, unknown: { $sum: { $cond: [{ $eq: ['$lastHeartbeatAt', null] }, 1, 0] } } } },
    ]).exec(),
  ]);

  const stats = totalStats[0] || { total: 0, active: 0, inactive: 0, blocked: 0, pending: 0, rejected: 0, online: 0, offline: 0 };
  const health = heartbeatStats[0] || { healthy: 0, unhealthy: 0, unknown: 0 };

  // Monthly device registration trends (last 6 months)
  const sixMonthsAgo = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000);
  const trendData = await Device.aggregate([
    { $match: { isDeleted: false, createdAt: { $gte: sixMonthsAgo } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();

  const trendMonths = Array.from({ length: 6 }, (_, i) => {
    const d = new Date(); d.setMonth(d.getMonth() - 5 + i);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  });
  const trendMap = new Map(trendData.map((r: any) => [r._id, r.count]));
  const trends = trendMonths.map((m) => ({ name: m, value: trendMap.get(m) || 0 }));

  return {
    total: stats.total,
    active: stats.active,
    inactive: stats.inactive,
    blocked: stats.blocked,
    pending: stats.pending,
    rejected: stats.rejected,
    online: stats.online,
    offline: stats.offline,
    health,
    byPlatform: platformStats.map((r: any) => ({ name: r._id || 'Unknown', value: r.count })),
    byStatus: statusStats.map((r: any) => ({ name: r._id, value: r.count })),
    trends,
  };
}

// ─── Growth Metrics ───────────────────────────────────────────

export async function getGrowthMetrics(): Promise<GrowthMetrics> {
  const { today, thisMonth, thisYear, lastYear } = getDateRanges();
  const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1000);
  const lastWeek = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);

  const [
    restaurantsToday, restaurantsYesterday,
    restaurantsThisWeek, restaurantsLastWeek,
    restaurantsThisMonth, restaurantsLastMonth,
    restaurantsThisYear, restaurantsLastYear,
    revenueToday, revenueYesterday,
    revenueThisWeek, revenueLastWeek,
    revenueThisMonth, revenueLastMonth,
    revenueThisYear, revenueLastYear,
    usersToday, usersYesterday,
    usersThisWeek, usersLastWeek,
    usersThisMonth, usersLastMonth,
    usersThisYear, usersLastYear,
    devicesToday, devicesYesterday,
    devicesThisWeek, devicesLastWeek,
    devicesThisMonth, devicesLastMonth,
    devicesThisYear, devicesLastYear,
    aiToday, aiYesterday,
    aiThisWeek, aiLastWeek,
    aiThisMonth, aiLastMonth,
    aiThisYear, aiLastYear,
  ] = await Promise.all([
    // Restaurant growth
    Restaurant.countDocuments({ createdAt: { $gte: today }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: yesterday, $lt: today }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: lastWeek }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: new Date(lastWeek.getTime() - 7 * 24 * 60 * 60 * 1000), $lt: lastWeek }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: thisMonth }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: lastMonth, $lt: thisMonth }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: thisYear }, isDeleted: { $ne: true } }).exec(),
    Restaurant.countDocuments({ createdAt: { $gte: lastYear, $lt: thisYear }, isDeleted: { $ne: true } }).exec(),
    // Revenue growth
    Payment.countDocuments({ status: 'success', createdAt: { $gte: today } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: yesterday, $lt: today } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: lastWeek } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: new Date(lastWeek.getTime() - 7 * 24 * 60 * 60 * 1000), $lt: lastWeek } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: thisMonth } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: lastMonth, $lt: thisMonth } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: thisYear } }).exec(),
    Payment.countDocuments({ status: 'success', createdAt: { $gte: lastYear, $lt: thisYear } }).exec(),
    // User growth (owners)
    User.countDocuments({ role: 'owner', createdAt: { $gte: today }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: yesterday, $lt: today }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: lastWeek }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: new Date(lastWeek.getTime() - 7 * 24 * 60 * 60 * 1000), $lt: lastWeek }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: thisMonth }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: lastMonth, $lt: thisMonth }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: thisYear }, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', createdAt: { $gte: lastYear, $lt: thisYear }, isDeleted: { $ne: true } }).exec(),
    // Device growth
    Device.countDocuments({ createdAt: { $gte: today }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: yesterday, $lt: today }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: lastWeek }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: new Date(lastWeek.getTime() - 7 * 24 * 60 * 60 * 1000), $lt: lastWeek }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: thisMonth }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: lastMonth, $lt: thisMonth }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: thisYear }, isDeleted: false }).exec(),
    Device.countDocuments({ createdAt: { $gte: lastYear, $lt: thisYear }, isDeleted: false }).exec(),
    // AI usage growth
    AIUsageLog.countDocuments({ createdAt: { $gte: today } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: yesterday, $lt: today } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: lastWeek } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: new Date(lastWeek.getTime() - 7 * 24 * 60 * 60 * 1000), $lt: lastWeek } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: thisMonth } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: lastMonth, $lt: thisMonth } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: thisYear } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: lastYear, $lt: thisYear } }).exec(),
  ]);

  return {
    restaurantGrowth: {
      daily: calcGrowth(restaurantsToday, restaurantsYesterday),
      weekly: calcGrowth(restaurantsThisWeek, restaurantsLastWeek),
      monthly: calcGrowth(restaurantsThisMonth, restaurantsLastMonth),
      yearly: calcGrowth(restaurantsThisYear, restaurantsLastYear),
    },
    revenueGrowth: {
      daily: calcGrowth(revenueToday, revenueYesterday),
      weekly: calcGrowth(revenueThisWeek, revenueLastWeek),
      monthly: calcGrowth(revenueThisMonth, revenueLastMonth),
      yearly: calcGrowth(revenueThisYear, revenueLastYear),
    },
    userGrowth: {
      daily: calcGrowth(usersToday, usersYesterday),
      weekly: calcGrowth(usersThisWeek, usersLastWeek),
      monthly: calcGrowth(usersThisMonth, usersLastMonth),
      yearly: calcGrowth(usersThisYear, usersLastYear),
    },
    deviceGrowth: {
      daily: calcGrowth(devicesToday, devicesYesterday),
      weekly: calcGrowth(devicesThisWeek, devicesLastWeek),
      monthly: calcGrowth(devicesThisMonth, devicesLastMonth),
      yearly: calcGrowth(devicesThisYear, devicesLastYear),
    },
    aiUsageGrowth: {
      daily: calcGrowth(aiToday, aiYesterday),
      weekly: calcGrowth(aiThisWeek, aiLastWeek),
      monthly: calcGrowth(aiThisMonth, aiLastMonth),
      yearly: calcGrowth(aiThisYear, aiLastYear),
    },
  };
}

// ─── Churn Metrics ────────────────────────────────────────────

export async function getChurnMetrics(): Promise<ChurnMetrics> {
  const { today, thirtyDaysAgo, oneYearAgo } = getDateRanges();
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);

  const [
    suspendedRestaurants,
    totalSubscriptions,
    cancelledOrExpired,
    trialSubscriptions,
    convertedTrials,
    failedRenewals,
    inactiveRestaurants,
    monthlyChurn,
  ] = await Promise.all([
    Restaurant.countDocuments({ isActive: false, isDeleted: { $ne: true } }).exec(),
    Subscription.countDocuments({}).exec(),
    Subscription.countDocuments({ status: { $in: ['cancelled', 'expired'] as unknown as SubscriptionStatus[] } }).exec(),
    Subscription.countDocuments({ status: 'trial' }).exec(),
    Subscription.countDocuments({ status: 'active', createdAt: { $gte: thirtyDaysAgo }, planId: { $ne: null } }).exec(),
    Payment.countDocuments({ status: 'failed', createdAt: { $gte: thirtyDaysAgo } }).exec(),
    Restaurant.countDocuments({ isActive: false, isDeleted: { $ne: true }, updatedAt: { $gte: thirtyDaysAgo } }).exec(),
    Subscription.aggregate([
      { $match: { status: { $in: ['cancelled', 'expired'] as unknown as SubscriptionStatus[] }, updatedAt: { $gte: oneYearAgo } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$updatedAt' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]).exec(),
  ]);

  const churnRate = totalSubscriptions > 0 ? Math.round((cancelledOrExpired / totalSubscriptions) * 100) : 0;
  const trialConversionRate = trialSubscriptions > 0 ? Math.round((convertedTrials / (trialSubscriptions + convertedTrials)) * 100) : 0;

  const months = Array.from({ length: 12 }, (_, i) => {
    const d = new Date(); d.setMonth(d.getMonth() - 11 + i);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  });
  const churnMap = new Map(monthlyChurn.map((r: any) => [r._id, r.count]));
  const churnByMonth = months.map((m) => ({ name: m, value: churnMap.get(m) || 0 }));

  return {
    suspendedRestaurants,
    subscriptionChurn: { total: cancelledOrExpired, rate: churnRate },
    trialConversions: { total: trialSubscriptions, converted: convertedTrials, rate: trialConversionRate },
    failedRenewals,
    inactiveRestaurants,
    churnRate,
    churnByMonth,
  };
}

// ─── Activity Metrics ─────────────────────────────────────────

export async function getActivityMetrics(): Promise<ActivityMetrics> {
  const { today, thisWeek, thisMonth, thirtyDaysAgo } = getDateRanges();

  const [
    dailyLogins, weeklyLogins, monthlyLogins,
    activeUsers, activeOwners, recentActivity,
    ownerDaily, deviceDaily, aiDaily,
    ownerWeekly, deviceWeekly, aiWeekly,
    ownerMonthly, deviceMonthly, aiMonthly,
  ] = await Promise.all([
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: today } }).exec(),
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: thisWeek } }).exec(),
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: thisMonth } }).exec(),
    User.countDocuments({ isActive: true, isDeleted: { $ne: true } }).exec(),
    User.countDocuments({ role: 'owner', isActive: true, isDeleted: { $ne: true } }).exec(),
    AuditLog.countDocuments({ createdAt: { $gte: thirtyDaysAgo } }).exec(),
    // Owner activity
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: today }, performedBy: { $exists: true } }).exec(),
    Device.countDocuments({ status: 'active', isDeleted: false, lastActivityAt: { $gte: today } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: today } }).exec(),
    // Weekly
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: thisWeek }, performedBy: { $exists: true } }).exec(),
    Device.countDocuments({ status: 'active', isDeleted: false, lastActivityAt: { $gte: thisWeek } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: thisWeek } }).exec(),
    // Monthly
    AuditLog.countDocuments({ action: { $regex: /LOGIN|login/i }, createdAt: { $gte: thisMonth }, performedBy: { $exists: true } }).exec(),
    Device.countDocuments({ status: 'active', isDeleted: false, lastActivityAt: { $gte: thisMonth } }).exec(),
    AIUsageLog.countDocuments({ createdAt: { $gte: thisMonth } }).exec(),
  ]);

  return {
    dailyLogins,
    weeklyLogins,
    monthlyLogins,
    activeUsers,
    activeOwners,
    recentActivity,
    ownerActivity: { daily: ownerDaily, weekly: ownerWeekly, monthly: ownerMonthly },
    deviceActivity: { daily: deviceDaily, weekly: deviceWeekly, monthly: deviceMonthly },
    aiActivity: { daily: aiDaily, weekly: aiWeekly, monthly: aiMonthly },
  };
}

// ─── Subscription Revenue ─────────────────────────────────────

export async function getSubscriptionRevenue(
  startDateParam?: string,
  endDateParam?: string
): Promise<RevenueMetrics> {
  const now = new Date();
  let startDate: Date;
  let endDate: Date;

  if (startDateParam) {
    startDate = new Date(startDateParam);
    if (isNaN(startDate.getTime())) startDate = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
  } else {
    startDate = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
  }

  if (endDateParam) {
    endDate = new Date(endDateParam);
    if (isNaN(endDate.getTime())) endDate = now;
    endDate.setHours(23, 59, 59, 999);
  } else {
    endDate = now;
  }

  const dateFilter = { $gte: startDate, $lte: endDate };

  // Aggregate by gateway
  const gatewayAgg = await Payment.aggregate([
    { $match: { status: 'success', createdAt: dateFilter } },
    {
      $group: {
        _id: { $cond: [{ $in: ['$gateway', ['cash', 'manual']] }, 'cash', 'razorpay'] },
        revenue: { $sum: '$amount' },
        count: { $sum: 1 },
      },
    },
  ]).exec();

  const cashData = gatewayAgg.find((r: any) => r._id === 'cash');
  const razorpayData = gatewayAgg.find((r: any) => r._id === 'razorpay');
  const cashRevenue = cashData?.revenue || 0;
  const cashCount = cashData?.count || 0;
  const razorpayRevenue = razorpayData?.revenue || 0;
  const razorpayCount = razorpayData?.count || 0;
  const totalRevenue = cashRevenue + razorpayRevenue;
  const totalCount = cashCount + razorpayCount;

  // Monthly breakdown
  const monthlyData = await Payment.aggregate([
    { $match: { status: 'success', createdAt: dateFilter } },
    {
      $group: {
        _id: {
          month: { $dateToString: { format: '%Y-%m', date: '$createdAt' } },
          isCash: { $in: ['$gateway', ['cash', 'manual']] },
        },
        revenue: { $sum: '$amount' },
        count: { $sum: 1 },
      },
    },
    { $sort: { '_id.month': 1 } },
  ]).exec();

  const monthlyMap: Record<string, { cash: number; razorpay: number; cashCount: number; razorpayCount: number }> = {};
  monthlyData.forEach((r: any) => {
    if (!monthlyMap[r._id.month]) {
      monthlyMap[r._id.month] = { cash: 0, razorpay: 0, cashCount: 0, razorpayCount: 0 };
    }
    if (r._id.isCash) {
      monthlyMap[r._id.month].cash += r.revenue;
      monthlyMap[r._id.month].cashCount += r.count;
    } else {
      monthlyMap[r._id.month].razorpay += r.revenue;
      monthlyMap[r._id.month].razorpayCount += r.count;
    }
  });

  const monthly = Object.entries(monthlyMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([month, data]) => ({
      month, cash: data.cash, razorpay: data.razorpay,
      cashCount: data.cashCount, razorpayCount: data.razorpayCount,
      total: data.cash + data.razorpay,
    }));

  // Recent payments
  const recentPayments = await Payment.find({ status: 'success', createdAt: dateFilter } as any)
    .sort({ createdAt: -1 }).limit(20).lean().exec() as any[];

  const recent = recentPayments.map((p) => ({
    id: p._id.toString(),
    invoiceNumber: p.invoiceNumber || '',
    amount: p.amount,
    gateway: p.gateway,
    paymentMethod: p.paymentMethod || p.gateway,
    createdAt: p.createdAt?.toISOString?.() || String(p.createdAt),
  }));

  return {
    total: { revenue: totalRevenue, count: totalCount },
    cash: { revenue: cashRevenue, count: cashCount, percentage: totalRevenue > 0 ? Math.round((cashRevenue / totalRevenue) * 100) : 0 },
    razorpay: { revenue: razorpayRevenue, count: razorpayCount, percentage: totalRevenue > 0 ? Math.round((razorpayRevenue / totalRevenue) * 100) : 0 },
    monthly,
    daily: [],
    weekly: [],
    yearly: [],
    byPaymentMethod: [
      { name: 'Cash / Manual', value: cashRevenue },
      { name: 'Razorpay Online', value: razorpayRevenue },
    ],
    recent,
  };
}

// ─── API Request Analytics ────────────────────────────────────

export async function getApiRequestAnalytics(days: number = 30): Promise<ApiRequestAnalytics> {
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);

  const totalRequests = await AuditLog.countDocuments({ createdAt: { $gte: since } }).exec();

  const perEndpoint = await AuditLog.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: '$action', count: { $sum: 1 } } },
    { $sort: { count: -1 } },
    { $limit: 20 },
  ]).exec();

  const errorCount = await AuditLog.countDocuments({
    createdAt: { $gte: since },
    action: { $regex: /ERROR|FAIL|DENIED|REJECTED/i },
  }).exec();

  const successRate = totalRequests > 0 ? Math.round(((totalRequests - errorCount) / totalRequests) * 100) : 0;
  const errorRate = totalRequests > 0 ? Math.round((errorCount / totalRequests) * 100) : 0;

  const latencyStats = await AIUsageLog.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: null, avg: { $avg: '$latencyMs' }, count: { $sum: 1 } } },
  ]).exec();

  const averageLatency = latencyStats.length > 0 ? Math.round(latencyStats[0].avg) : 0;

  const dailyData = await AuditLog.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]).exec();

  const dailyMap = new Map(dailyData.map((r: any) => [r._id, r.count]));
  const daysArr = getDaysArray(days);
  const daily = daysArr.map((d) => ({ name: d, value: dailyMap.get(d) || 0 }));

  return {
    totalRequests,
    requestsPerEndpoint: perEndpoint.map((r: any) => ({ endpoint: r._id, count: r.count })),
    successRate,
    errorRate,
    averageLatency,
    slowEndpoints: [],
    daily,
  };
}
