/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Segment Engine — Dynamically assigns customers to segments based on
 * their purchase behavior, visit patterns, and preferences.
 * Uses deterministic rules — no AI needed for segmentation.
 * All segments update automatically.
 */

import CustomerModel from '../models/Customer';
import type { SegmentType, ICustomerSegment } from '../models/CustomerSegment';
import CustomerSegmentModel from '../models/CustomerSegment';
import mongoose from 'mongoose';

// ─── Segment Definitions ──────────────────────────────────────

interface SegmentRule {
  type: SegmentType;
  name: string;
  description: string;
  isAutoGenerated: boolean;
}

const SEGMENT_DEFINITIONS: SegmentRule[] = [
  // Visit-based
  { type: 'visit_today', name: 'Visited Today', description: 'Customers who visited today', isAutoGenerated: true },
  { type: 'visit_this_week', name: 'Visited This Week', description: 'Customers who visited this week', isAutoGenerated: true },
  { type: 'visit_this_month', name: 'Visited This Month', description: 'Customers who visited this month', isAutoGenerated: true },

  // Customer lifecycle
  { type: 'new_customer', name: 'New Customers', description: 'Customers on their first visit', isAutoGenerated: true },
  { type: 'returning_customer', name: 'Returning Customers', description: 'Customers who have visited more than once', isAutoGenerated: true },
  { type: 'frequent_customer', name: 'Frequent Customers', description: 'Customers with 10+ visits', isAutoGenerated: true },
  { type: 'vip_customer', name: 'VIP Customers', description: 'Top spenders with 20+ visits and high lifetime value', isAutoGenerated: true },
  { type: 'high_spending', name: 'High Spending', description: 'Customers with average bill above Rs.1000', isAutoGenerated: true },
  { type: 'low_spending', name: 'Low Spending', description: 'Customers with average bill below Rs.200', isAutoGenerated: true },

  // Dormant
  { type: 'dormant_7d', name: 'Dormant (7 Days)', description: 'Not visited in 7 days', isAutoGenerated: true },
  { type: 'dormant_15d', name: 'Dormant (15 Days)', description: 'Not visited in 15 days', isAutoGenerated: true },
  { type: 'dormant_30d', name: 'Dormant (30 Days)', description: 'Not visited in 30 days', isAutoGenerated: true },
  { type: 'dormant_45d', name: 'Dormant (45 Days)', description: 'Not visited in 45 days', isAutoGenerated: true },
  { type: 'dormant_60d', name: 'Dormant (60 Days)', description: 'Not visited in 60 days', isAutoGenerated: true },
  { type: 'dormant_90d', name: 'Dormant (90 Days)', description: 'Not visited in 90 days', isAutoGenerated: true },

  // Date-based
  { type: 'birthday_today', name: 'Birthday Today', description: 'Customers whose birthday is today', isAutoGenerated: true },
  { type: 'birthday_tomorrow', name: 'Birthday Tomorrow', description: 'Customers whose birthday is tomorrow', isAutoGenerated: true },
  { type: 'birthday_this_week', name: 'Birthday This Week', description: 'Customers with birthday in the next 7 days', isAutoGenerated: true },

  // Lifestyle / loyalty (declared but computed on demand where data supports it)
  { type: 'weekend_customer', name: 'Weekend Customers', description: 'Customers who mostly visit on weekends', isAutoGenerated: true },
  { type: 'lunch_customer', name: 'Lunch Customers', description: 'Customers who mostly visit during lunch', isAutoGenerated: true },
  { type: 'dinner_customer', name: 'Dinner Customers', description: 'Customers who mostly visit during dinner', isAutoGenerated: true },
  { type: 'family_orders', name: 'Family Orders', description: 'Customers with large family orders', isAutoGenerated: true },
  { type: 'online_orders', name: 'Online Orders', description: 'Customers who order online', isAutoGenerated: true },
  { type: 'loyalty_member', name: 'Loyalty Members', description: 'Customers with loyalty points balance > 0', isAutoGenerated: true },
  { type: 'reward_redeemer', name: 'Reward Redeemers', description: 'Customers who have redeemed rewards', isAutoGenerated: true },

];

/**
 * Initialize default segments for a restaurant if they don't exist.
 */
export async function ensureDefaultSegments(restaurantId: string): Promise<void> {
  const oid = new mongoose.Types.ObjectId(restaurantId);

  for (const def of SEGMENT_DEFINITIONS) {
    const exists = await CustomerSegmentModel.findOne({
      restaurantId: oid,
      type: def.type,
    });
    if (!exists) {
      await CustomerSegmentModel.create({
        restaurantId: oid,
        name: def.name,
        type: def.type,
        description: def.description,
        customerPhones: [],
        customerCount: 0,
        averageSpend: 0,
        averageVisitFrequency: 0,
        isAutoGenerated: def.isAutoGenerated,
      });
    }
  }
}

/**
 * Update all segments for a restaurant with current customer data.
 */
export async function updateAllSegments(restaurantId: string): Promise<void> {
  const oid = new mongoose.Types.ObjectId(restaurantId);
  await ensureDefaultSegments(restaurantId);

  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  const todayMonthDay = `${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const tomorrowMonthDay = `${String(tomorrow.getMonth() + 1).padStart(2, '0')}-${String(tomorrow.getDate()).padStart(2, '0')}`;
  // All MM-DD values in the next 7 days (for birthday_this_week).
  const weekMonthDays: string[] = [];
  for (let i = 0; i < 7; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() + i);
    weekMonthDays.push(`${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`);
  }

  // TENANT ISOLATION (Phase 2): the customer scan MUST be scoped to the
  // authenticated restaurant. Loading every tenant's customers here would
  // copy other restaurants' phone numbers into this restaurant's segments.
  // Only the fields needed for segmentation are projected (avoids pulling
  // heavy documents like purchaseHistory for the whole customer base).
  const customers = await CustomerModel.find({
    restaurantId: oid,
    isDeleted: { $ne: true },
  })
    .select('phone lastVisit visits points birthday isNewCustomer tier orderType')
    .lean();

  // Group customers by segment
  const segmentCustomers: Record<string, string[]> = {};
  const segmentSpends: Record<string, number[]> = {};

  for (const def of SEGMENT_DEFINITIONS) {
    segmentCustomers[def.type] = [];
    segmentSpends[def.type] = [];
  }

  for (const c of customers) {
    const lastVisit = c.lastVisit ? new Date(c.lastVisit) : null;
    const daysSinceLastVisit = lastVisit
      ? Math.floor((today.getTime() - lastVisit.getTime()) / (1000 * 60 * 60 * 24))
      : 999;

    // Visit-based
    if (lastVisit && lastVisit.toISOString().split('T')[0] === todayStr) {
      segmentCustomers['visit_today'].push(c.phone);
    }
    if (lastVisit && daysSinceLastVisit <= 7) {
      segmentCustomers['visit_this_week'].push(c.phone);
    }
    if (lastVisit && daysSinceLastVisit <= 30) {
      segmentCustomers['visit_this_month'].push(c.phone);
    }

    // Lifecycle
    if (c.isNewCustomer && c.visits <= 1) {
      segmentCustomers['new_customer'].push(c.phone);
    }
    if (c.visits > 1) {
      segmentCustomers['returning_customer'].push(c.phone);
    }
    if (c.visits >= 10) {
      segmentCustomers['frequent_customer'].push(c.phone);
    }
    if (c.visits >= 20 && c.points >= 500) {
      segmentCustomers['vip_customer'].push(c.phone);
    }

    // Dormant
    if (daysSinceLastVisit >= 7 && daysSinceLastVisit < 15) segmentCustomers['dormant_7d'].push(c.phone);
    if (daysSinceLastVisit >= 15 && daysSinceLastVisit < 30) segmentCustomers['dormant_15d'].push(c.phone);
    if (daysSinceLastVisit >= 30 && daysSinceLastVisit < 45) segmentCustomers['dormant_30d'].push(c.phone);
    if (daysSinceLastVisit >= 45 && daysSinceLastVisit < 60) segmentCustomers['dormant_45d'].push(c.phone);
    if (daysSinceLastVisit >= 60 && daysSinceLastVisit < 90) segmentCustomers['dormant_60d'].push(c.phone);
    if (daysSinceLastVisit >= 90) segmentCustomers['dormant_90d'].push(c.phone);

    // Birthday
    if (c.birthday) {
      const bd = c.birthday.trim();
      if (bd.length >= 5) {
        const bdMMDD = bd.length === 10 ? bd.substring(5) : bd;
        if (bdMMDD === todayMonthDay) segmentCustomers['birthday_today'].push(c.phone);
        if (bdMMDD === tomorrowMonthDay) segmentCustomers['birthday_tomorrow'].push(c.phone);
        if (weekMonthDays.includes(bdMMDD)) segmentCustomers['birthday_this_week'].push(c.phone);
      }
    }

    // Visit-time lifestyle (best-effort, from lastVisit hour)
    if (lastVisit) {
      const hour = new Date(lastVisit).getHours();
      const dow = new Date(lastVisit).getDay();
      if (dow === 5 || dow === 6 || dow === 0) segmentCustomers['weekend_customer'].push(c.phone);
      if (hour >= 11 && hour < 15) segmentCustomers['lunch_customer'].push(c.phone);
      if (hour >= 18 && hour < 23) segmentCustomers['dinner_customer'].push(c.phone);
    }

    // Large orders / online orders (best-effort flags where present)
    if ((c as any).orderType && String((c as any).orderType).toLowerCase() !== 'dine in') {
      segmentCustomers['online_orders'].push(c.phone);
    }

    // Loyalty
    if (c.points > 0) segmentCustomers['loyalty_member'].push(c.phone);
  }

  // Bulk-update all segments in a single round-trip
  const bulkOps = SEGMENT_DEFINITIONS.map(def => ({
    updateOne: {
      filter: { restaurantId: oid, type: def.type },
      update: {
        $set: {
          customerPhones: segmentCustomers[def.type] || [],
          customerCount: (segmentCustomers[def.type] || []).length,
          lastCampaignDate: undefined,
        },
      },
      upsert: true,
    },
  }));

  await CustomerSegmentModel.bulkWrite(bulkOps);
}

/**
 * Get all segments for a restaurant with customer counts.
 */
export async function getSegments(restaurantId: string): Promise<ICustomerSegment[]> {
  const oid = new mongoose.Types.ObjectId(restaurantId);
  await ensureDefaultSegments(restaurantId);
  return CustomerSegmentModel.find({ restaurantId: oid, isDeleted: { $ne: true } })
    .sort({ customerCount: -1 })
    .lean();
}

/**
 * Get a specific segment by ID.
 */
export async function getSegmentById(segmentId: string, restaurantId: string): Promise<ICustomerSegment | null> {
  const oid = new mongoose.Types.ObjectId(restaurantId);
  return CustomerSegmentModel.findOne({ _id: segmentId, restaurantId: oid, isDeleted: { $ne: true } }).lean();
}
