/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Promotion Model — the creative layer that turns an existing Offer into a
 * branded, customer-ready promotion (banner / card / QR creative).
 *
 * Design rules (Phase C):
 *   - The Offer is the financial source of truth. A Promotion only references
 *     it (offerId) and never stores prices/discounts of its own.
 *   - `offerSnapshot` records the offer state at the time the creative was
 *     generated so the POS can detect when the creative has gone stale
 *     (offer edited after the creative was made) — see
 *     promotionService.checkMismatch.
 *   - `creative.content` holds presentation-only text/images chosen by the
 *     owner or generated by AI (AI is advisory; never financial authority).
 *   - Media references reuse the existing upload system (MediaService) — the
 *     key + metadata are stored here, never a second media store.
 */

import mongoose, { Schema, Document } from 'mongoose';

export type PromotionStatus = 'draft' | 'published' | 'archived';
export type PromotionChannel = 'website' | 'qr';
export type CreativeImageSource = 'product' | 'restaurant' | 'uploaded' | 'generated' | 'template';
export type CreativeGeneratedBy = 'ai' | 'template' | 'manual';

export interface PromotionCreativeMediaRef {
  /** Relative public URL (/uploads/restaurants/...) from the media module. */
  key: string;
  source: CreativeImageSource;
  originalName?: string;
  mimetype?: string;
  size?: number;
  productId?: string;
  offerId?: string;
}

export interface PromotionCreativeContent {
  title: string;
  subtitle: string;
  description: string;
  cta: string;
  language: string;   // 'en' | 'hi' | 'hinglish'
  tone: string;       // professional | friendly | fun | premium | genz | minimal
  templateId: string;
  /** Hex colors chosen by the owner (presentation only). */
  colors: { background: string; text: string; accent: string };
  /** Primary image for the creative (used on every screen unless overridden). */
  image?: PromotionCreativeMediaRef | null;
  /**
   * Per-screen image overrides, keyed by template/screen id
   * (hero-banner | offer-card | square-creative | mobile-banner). An absent
   * entry means that screen uses the primary `image` — "same image for all"
   * is the default; only screens the owner customized appear here. Purely
   * presentation data, never financial.
   */
  screenImages?: Record<string, PromotionCreativeMediaRef> | null;
  /** Restaurant logo key (falls back to the restaurant's own logoUrl). */
  logoKey?: string | null;
  /** Product image keys selected for the creative. */
  productImageKeys: string[];
  /** Free-form layout hint consumed by the frontend renderer. */
  layout: string;
}

export interface IOfferSnapshot {
  offerId: string;
  offerTitle: string;
  type: string;
  value: number;
  minOrderValue?: number;
  discountDisplay: string;
  startDate?: string;
  endDate?: string;
  offerUpdatedAt?: Date;
}

export interface IPromotion extends Document {
  restaurantId: mongoose.Types.ObjectId;
  offerId: mongoose.Types.ObjectId;
  name: string;
  status: PromotionStatus;
  channels: PromotionChannel[];
  templateId: string;
  creative: PromotionCreativeContent;
  offerSnapshot: IOfferSnapshot;
  generatedBy: CreativeGeneratedBy;
  publishedAt?: Date;
  isDeleted: boolean;
  deletedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const PromotionSchema = new Schema<IPromotion>(
  {
    restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true, index: true },
    offerId: { type: Schema.Types.ObjectId, ref: 'Offer', required: true },
    name: { type: String, required: true, trim: true, maxlength: 120 },
    status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft' },
    channels: { type: [String], enum: ['website', 'qr'], default: ['website'] },
    templateId: { type: String, required: true, trim: true },
    creative: {
      title: { type: String, trim: true, default: '' },
      subtitle: { type: String, trim: true, default: '' },
      description: { type: String, trim: true, default: '' },
      cta: { type: String, trim: true, default: 'Order Now' },
      language: { type: String, enum: ['en', 'hi', 'hinglish'], default: 'en' },
      tone: { type: String, trim: true, default: 'friendly' },
      templateId: { type: String, trim: true, default: '' },
      colors: {
        background: { type: String, trim: true, default: '#0b2a5b' },
        text: { type: String, trim: true, default: '#ffffff' },
        accent: { type: String, trim: true, default: '#f59e0b' },
      },
      image: {
        key: String,
        source: { type: String, enum: ['product', 'restaurant', 'uploaded', 'generated', 'template'] },
        originalName: String,
        mimetype: String,
        size: Number,
        productId: String,
        offerId: String,
      },
      // Per-screen image overrides (same media-ref shape as `image`).
      screenImages: {
        type: Map,
        of: new Schema({
          key: String,
          source: { type: String, enum: ['product', 'restaurant', 'uploaded', 'generated', 'template'] },
          originalName: String,
          mimetype: String,
          size: Number,
          productId: String,
          offerId: String,
        }, { _id: false }),
        default: undefined,
      },
      logoKey: { type: String, default: null },
      productImageKeys: { type: [String], default: [] },
      layout: { type: String, trim: true, default: 'hero' },
    },
    offerSnapshot: {
      offerId: String,
      offerTitle: String,
      // `type` must be escaped — mongoose reads a bare `type` key as the
      // field type declaration and would swallow the whole nested object.
      type: { type: String },
      value: Number,
      minOrderValue: Number,
      discountDisplay: String,
      startDate: String,
      endDate: String,
      offerUpdatedAt: Date,
    },
    generatedBy: { type: String, enum: ['ai', 'template', 'manual'], default: 'manual' },
    publishedAt: { type: Date, default: null },
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// Phase C — query indexes (restaurant-prefixed, matching Offer conventions).
PromotionSchema.index({ restaurantId: 1, status: 1 });
PromotionSchema.index({ restaurantId: 1, offerId: 1 });
PromotionSchema.index({ restaurantId: 1, createdAt: -1 });
PromotionSchema.index({ restaurantId: 1, status: 1, publishedAt: -1 });

export default mongoose.model<IPromotion>('Promotion', PromotionSchema);
