/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * publicToken — shareable identifier that opens a restaurant's public loyalty
 * store. Embedded in the QR codes generated by the POS / dashboard. It is NOT a
 * secret: it only exposes the public (read-only) store, never POS/admin data.
 *
 * Moved here (instead of restaurantService) so settingsService and the public
 * store module can reuse it WITHOUT a circular import (restaurantService itself
 * imports settingsService).
 */

import crypto from 'crypto';
import Restaurant from '../models/Restaurant';

/** Mint a new public token (cryptographic random, URL-safe-ish). */
export function generatePublicToken(): string {
  return `pbl_${crypto.randomBytes(12).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(-22)}`;
}

/**
 * Guarantee a restaurant has a public token (minted once, never rotated).
 * Atomic so concurrent "first read" requests cannot mint two tokens for the same
 * tenant. Returns the existing token when already present.
 */
export async function ensurePublicToken(restaurantId: string): Promise<string> {
  const existing = await Restaurant.findOne({ _id: restaurantId, publicToken: { $exists: true, $ne: null } })
    .select('_id publicToken') as any;
  if (existing?.publicToken) return existing.publicToken;
  const doc = await Restaurant.findOneAndUpdate(
    { _id: restaurantId, publicToken: null },
    { $set: { publicToken: generatePublicToken() } },
    { new: true, runValidators: false }
  ).exec();
  return doc?.publicToken || '';
}