import { beforeAll, afterAll, beforeEach, describe, expect, it } from 'vitest';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

import Bill from '../../../models/Bill';
import BillItem from '../../../models/BillItem';
import CashLedger from '../../../models/CashLedger';
import MonthlySummary from '../../../models/MonthlySummary';
import YearlySummary from '../../../models/YearlySummary';
import DailySummary from '../../../models/DailySummary';
import { closingReportService, summaryService } from '../services';
import { buildCsv, buildXlsx, buildPdf, streamCsv } from '../services/exportService';

let mongod: MongoMemoryServer;
const REST_A = new mongoose.Types.ObjectId().toString();

async function seedBill(grandTotal: number, over: any = {}) {
  return Bill.create({
    invoiceNumber: `INV-${Math.floor(Math.random() * 1e6)}`,
    ticketNumber: 'T-1',
    date: '2026-08-01',
    time: '12:30',
    cashierName: 'Owner',
    cashierRole: 'Owner',
    subtotal: grandTotal,
    discount: 0,
    gst: 0,
    grandTotal,
    paymentMethod: 'Cash',
    orderType: 'Dine In',
    restaurantId: REST_A,
    isVoided: false,
    isRefunded: false,
    refundAmount: 0,
    pointsEarned: 10,
    pointsRedeemed: 0,
    ...over,
  });
}

describe('Closing + Summary + Export (Phase 1.8)', () => {
  beforeAll(async () => {
    mongod = await MongoMemoryServer.create();
    await mongoose.connect(mongod.getUri());
  }, 60_000);

  afterAll(async () => {
    await mongoose.disconnect();
    await mongod.stop();
  });

  beforeEach(async () => {
    await Promise.all([
      Bill.deleteMany({}).exec(),
      BillItem.deleteMany({}).exec(),
      CashLedger.deleteMany({}).exec(),
      MonthlySummary.deleteMany({}).exec(),
      YearlySummary.deleteMany({}).exec(),
      DailySummary.deleteMany({}).exec(),
    ]);
  });

  it('produces an X report with cash drawer totals', async () => {
    await seedBill(1000);
    await CashLedger.create({ restaurantId: REST_A, type: 'opening', amount: 500, balanceAfter: 500, date: '2026-08-01', note: 'Opening' });

    const x: any = await closingReportService.xReport({ restaurantId: REST_A }, '2026-08-01');
    expect(x.reportType).toBe('X');
    expect(x.sales.orders).toBe(1);
    expect(x.sales.grossRevenue).toBe(1000);
    expect(x.sales.payments[0].method).toBe('Cash');
  });

  it('produces a Z report with expected vs actual cash reconciliation', async () => {
    await seedBill(1000);
    await CashLedger.create({ restaurantId: REST_A, type: 'opening', amount: 500, balanceAfter: 500, date: '2026-08-01', note: 'Opening' });

    const z: any = await closingReportService.zReport({ restaurantId: REST_A }, '2026-08-01');
    expect(z.reportType).toBe('Z');
    expect(z.cash.openingCash).toBe(500);
    expect(z.cash.cashSales).toBe(1000);
    expect(typeof z.cash.expectedCash).toBe('number');
    expect(typeof z.cash.overShort).toBe('number');
  });

  it('rebuilds monthly and yearly summaries from bills', async () => {
    await seedBill(1000);
    await seedBill(2000, { paymentMethod: 'UPI' });

    const rebuilt = await summaryService.rebuild({ restaurantId: REST_A, startDate: '2026-08-01', endDate: '2026-08-31' });
    expect(rebuilt.rebuilt).toContain('2026-08');

    const monthly = await summaryService.monthly({ restaurantId: REST_A, startDate: '2026-08-01', endDate: '2026-08-31' });
    expect(monthly.data.length).toBe(1);
    expect(monthly.data[0].totalRevenue).toBe(3000);
    expect(monthly.data[0].totalOrders).toBe(2);

    const yearly = await summaryService.yearly({ restaurantId: REST_A, startDate: '2026-01-01', endDate: '2026-12-31' });
    expect(yearly.data.length).toBe(1);
    expect(yearly.data[0].year).toBe('2026');
  });

  it('reads materialized daily summaries', async () => {
    await DailySummary.create({ date: '2026-08-01', restaurantId: REST_A, totalRevenue: 500, totalOrders: 3, totalItemsSold: 5, totalDiscount: 10, totalGst: 25, averageOrderValue: 166.67 } as any);
    const daily = await summaryService.daily({ restaurantId: REST_A, startDate: '2026-08-01', endDate: '2026-08-01' });
    expect(daily.total).toBe(1);
    expect(daily.data[0].totalRevenue).toBe(500);
  });

  it('builds CSV / XLSX / PDF exports from the same data', async () => {
    const table = {
      headers: ['Name', 'Qty', 'Revenue'],
      rows: [['Pizza', 4, 2000]],
      totals: ['TOTAL', 4, 2000],
    };
    const meta = { title: 'Product Report', restaurantName: 'Test Restaurant', generatedAt: new Date().toISOString(), filters: { Range: '2026-08-01 → 2026-08-01' }, footer: 'Generated by POS' };

    const csv = buildCsv(table, meta);
    expect(csv).toContain('Product Report');
    expect(csv).toContain('Pizza,4,2000');
    expect(csv).toContain('TOTAL');

    const stream = streamCsv(table, meta);
    const chunks: Buffer[] = [];
    for await (const c of stream as any) chunks.push(Buffer.from(c));
    expect(Buffer.concat(chunks).toString()).toContain('Pizza');

    const xlsx = await buildXlsx(table, meta);
    expect(xlsx.length).toBeGreaterThan(100);

    const pdf = await buildPdf(table, meta);
    expect(pdf.length).toBeGreaterThan(500);
  });
});
