/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Phase 6 — Promotion Orchestration Tests
 * Tests for CampaignProposal validation, conflict detection, frequency check,
 * economics calculation, quiet periods, consent/opt-out, and natural language commands.
 */

import mongoose from 'mongoose';
import { objectId } from '../validation/common';
import { CampaignProposal, CampaignProposalObjective, CampaignProposalStrategy, CampaignProposalApprovalStatus, CampaignProposalExecutionStatus } from '../../models/CampaignProposal';
import { CampaignService } from '../../services';
import { Restaurant } from '../../models';
import { CustomerSegment } from '../../models';
import { Offer } from '../../models';

const restaurantId = new mongoose.Types.ObjectId();

let campaignService: CampaignService;
let restaurant: any;

beforeAll(async () => {
  // Create a test restaurant
  restaurant = new Restaurant({
    restaurantId,
    name: 'Test Restaurant',
    address: 'Test Address',
    city: 'Test City',
    country: 'Test Country',
    phone: '1234567890',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    locale: 'en-IN',
    isDeleted: false,
  });
  await restaurant.save();

  // Create test customer segments
  await CustomerSegment.create({
    restaurantId,
    name: 'dormant_30d',
    type: 'dormant_30d',
    description: 'Customers inactive for 30+ days',
    customerPhones: ['9876543210', '8765432109'],
    customerCount: 2,
    isAutoGenerated: true,
    isDeleted: false,
  });

  await CustomerSegment.create({
    restaurantId,
    name: 'vip_customer',
    type: 'vip_customer',
    description: 'VIP customers',
    customerPhones: ['9123456780'],
    customerCount: 1,
    isAutoGenerated: true,
    isDeleted: false,
  });

  // Create a test offer
  await Offer.create({
    restaurantId,
    title: 'Test Discount Offer',
    description: 'A test discount offer',
    type: 'percentage',
    value: 10,
    minOrderValue: 0,
    maxDiscount: 50,
    maxUses: 1000,
    currentUses: 0,
    maxPerCustomer: undefined,
    applicableCategories: [],
    applicableProductIds: [],
    targetSegmentIds: [],
    targetSegmentNames: [],
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    scheduledDate: undefined,
    daysOfWeek: [],
    startHour: undefined,
    endHour: undefined,
    freeItemId: undefined,
    freeItemName: undefined,
    freeItemQty: undefined,
    comboProductIds: undefined,
    comboPrice: undefined,
    comboBranchPrices: {},
    linkedProductId: undefined,
    cashbackValue: undefined,
    referrerReward: undefined,
    refereeReward: undefined,
    couponCode: 'TEST10',
    targetTier: [],
    stackingAllowed: true,
    mutuallyExclusiveGroup: undefined,
    recommendationSource: 'manual',
    recommendationReason: 'Test offer',
    isAiGenerated: false,
    isAutoActivate: false,
    status: 'active',
    branchIds: [],
    imageUrl: undefined,
    sortOrder: 0,
    isDeleted: false,
  });

  campaignService = new CampaignService();
});

afterAll(async () => {
  // Cleanup
  await CampaignProposal.deleteMany({ restaurantId: restaurantId });
  await Offer.deleteMany({ restaurantId });
  await CustomerSegment.deleteMany({ restaurantId });
  await Restaurant.deleteOne({ restaurantId: restaurantId });
});

describe('CampaignProposal Model - validateCampaignProposal', () => {
  it('should validate a valid proposal', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Campaign',
      objective: 'INCREASE_AOV',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'immediate', scheduledAt: null, startDate: null, endDate: null, daysOfWeek: [], startHour: undefined, endHour: undefined, quietPeriods: [] },
      channels: ['whatsapp'],
      budgetLimits: { maxDiscountPercent: 20 },
      financialModel: { totalCost: 0, discountCost: 0, communicationCost: 0, freeItemCost: 0, expectedRevenue: 0, expectedIncrementalContribution: 0, expectedROI: 0, costBreakdown: { discountCost: 0, communicationCost: 0, freeItemCost: 0 }, confidence: 'low' },
      expectedImpact: { expectedReach: 100, expectedRedemptionRate: 10, expectedIncrementalOrders: 1, expectedAOVImpact: 0, expectedNewCustomers: 0, expectedRepeatVisits: 0 },
      evidence: { elasticityEstimate: undefined, historicalPromotionIds: [], dataSufficiency: 'INSUFFICIENT_DATA', modelVersion: 'v1' },
      risks: { marginRisk: 'low', cannibalizationRisk: 'low', fatigueRisk: 'low', conflictRisk: 'low', notes: [] },
      approvalStatus: 'pending',
      executionStatus: 'pending',
    });

    const result = await proposal.validateCampaignProposal();
    expect(result.valid).toBe(true);
    expect(result.errors.length).toBe(0);
  });

  it('should fail validation without an objective', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Campaign',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'immediate', scheduledAt: null, startDate: null, endDate: null, daysOfWeek: [], startHour: undefined, endHour: undefined, quietPeriods: [] },
      channels: ['whatsapp'],
    });

    const result = await proposal.validateCampaignProposal();
    expect(result.valid).toBe(false);
    expect(result.errors.includes('Objective is required')).toBe(true);
  });

  it('should fail validation without an audience', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Campaign',
      objective: 'INCREASE_AOV',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'immediate', scheduledAt: null, startDate: null, endDate: null, daysOfWeek: [], startHour: undefined, endHour: undefined, quietPeriods: [] },
      channels: [],
    });

    const result = await proposal.validateCampaignProposal();
    expect(result.valid).toBe(false);
    expect(result.errors.includes('At least one communication channel must be selected')).toBe(true);
  });

  it('should fail validation with invalid schedule', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Campaign',
      objective: 'INCREASE_AOV',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'scheduled', scheduledAt: null, startDate: new Date(), endDate: new Date(1) }, // start after end
      channels: ['whatsapp'],
    });

    const result = await proposal.validateCampaignProposal();
    expect(result.valid).toBe(false);
    expect(result.errors.includes('Start date must be before end date')).toBe(true);
  });

  it('should fail validation with empty audience', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Campaign',
      objective: 'INCREASE_AOV',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'immediate', scheduledAt: null, startDate: null, endDate: null, daysOfWeek: [], startHour: undefined, endHour: undefined, quietPeriods: [] },
      channels: ['whatsapp'],
    });

    const result = await proposal.validateCampaignProposal();
    expect(result.valid).toBe(false);
    expect(result.errors.includes('Audience must have at least one segment or customer phone')).toBe(true);
  });
});

describe('CampaignService - validateCampaignProposal', () => {
  it('should validate a campaign proposal with all required fields', async () => {
    const result = await campaignService.validateCampaignProposal(
      restaurantId.toString(),
      {
        name: 'Test Proposal',
        objective: 'INCREASE_AOV',
        strategy: 'DISCOUNT',
        offerId: undefined,
        audience: { segmentIds: [], segmentNames: [], customerPhones: ['9876543210'] },
        schedule: { mode: 'immediate' },
        channels: ['whatsapp'],
        budgetLimits: { maxDiscountPercent: 20 },
      },
      { operator: 'Test Owner' }
    );

    expect(typeof result.valid === 'boolean').toBe(true);
    expect(Array.isArray(result.errors)).toBe(true);
    expect(Array.isArray(result.warnings)).toBe(true);
  });

  it('should detect conflicts with existing proposals', async () => {
    const result = await campaignService.detectConflicts(
      restaurantId.toString(),
      {
        name: 'Test Conflict Proposal',
        objective: 'INCREASE_AOV',
        strategy: 'DISCOUNT',
        offerId: undefined,
        audience: { segmentIds: [], segmentNames: [], customerPhones: ['9876543210'] },
        schedule: { mode: 'immediate' },
        channels: ['whatsapp'],
      },
      { operator: 'Test Owner' }
    );

    expect(Array.isArray(result.conflicts)).toBe(true);
    expect(Array.isArray(result.warnings)).toBe(true);
  });

  it('should check customer contact frequency', async () => {
    const result = await campaignService.checkCustomerFrequency(
      restaurantId.toString(),
      { segmentIds: ['dormant_30d'], customerPhones: ['9876543210'] },
      { operator: 'Test Owner' }
    );

    expect(typeof result.exceedLimit === 'boolean').toBe(true);
    expect(typeof result.message === 'string').toBe(true);
    expect(typeof result.fatiguedCount === 'number').toBe(true);
  });

  it('should calculate campaign economics', async () => {
    const result = await campaignService.calculateCampaignEconomics(
      restaurantId.toString(),
      {
        objective: 'INCREASE_AOV',
        strategy: 'DISCOUNT',
        offerId: undefined,
        audience: { segmentIds: [], segmentNames: [], customerPhones: ['9876543210'] },
        channels: ['whatsapp'],
        budgetLimits: { maxDiscountPercent: 20, communicationCostCap: 5000 },
      },
      { operator: 'Test Owner' }
    );

    expect(typeof result.communicationCost === 'number').toBe(true);
    expect(typeof result.discountCost === 'number').toBe(true);
    expect(typeof result.totalCost === 'number').toBe(true);
    expect(typeof result.expectedIncrementalContribution === 'number').toBe(true);
    expect(typeof result.expectedROI === 'number').toBe(true);
    expect(typeof result.meetsBudget === 'boolean').toBe(true);
  });

  it('should check quiet period', async () => {
    const result = await campaignService.isQuietPeriod({
      mode: 'scheduled',
      quietPeriods: [{ startHour: 22, endHour: 9 }],
    });

    expect(typeof result === 'boolean').toBe(true);
  });

  it('should check consent/opt-out', async () => {
    const result = await campaignService.checkConsent(
      restaurantId.toString(),
      { customerPhones: ['9876543210'] },
      { operator: 'Test Owner' }
    );

    expect(typeof result.valid === 'boolean').toBe(true);
    expect(typeof result.excludedCount === 'number').toBe(true);
    expect(typeof result.message === 'string').toBe(true);
  });
});

describe('CampaignService - natural language commands', () => {
  it('should parse a command with objective and discount', async () => {
    const result = await campaignService.validateNaturalLanguageCommand(
      restaurantId.toString(),
      'Run a 20% off discount promotion for AOV increase on Tuesday 3-6 PM'
    );

    expect(typeof result.valid === 'boolean').toBe(true);
    expect(Array.isArray(result.errors)).toBe(true);
    // May or may not parse fully depending on NLP logic
  });

  it('should reject command without objective', async () => {
    const result = await campaignService.validateNaturalLanguageCommand(
      restaurantId.toString(),
      'Just a random promotion'
    );

    expect(result.valid).toBe(false);
    expect(result.errors.includes('Could not determine campaign objective')).toBe(true);
  });

  it('should create proposal from command', async () => {
    const result = await campaignService.createProposalFromCommand(
      restaurantId.toString(),
      'Create a Tuesday 3-6 PM Chai + Samosa promotion for inactive customers'
    );

    expect(result.proposal).not.toBeNull();
    expect(typeof result.validation.valid === 'boolean').toBe(true);
    expect(typeof result.message === 'string').toBe(true);
  });
});

describe('CampaignProposal - state transitions', () => {
  it('should allow pending → validating transition', async () => {
    const proposal = new CampaignProposal({
      restaurantId,
      name: 'Test Transition',
      objective: 'INCREASE_AOV',
      strategy: 'DISCOUNT',
      offerId: undefined,
      audience: { segmentIds: [], segmentNames: [], customerPhones: [] },
      schedule: { mode: 'immediate' },
      channels: ['whatsapp'],
    });

    // Start in pending state (default)
    expect(proposal.approvalStatus).toBe('pending');
  });

  it('should validate transition logic', () => {
    // Test the transition functions
    expect(campaignService.canApproveTransition('pending', 'validating')).toBe(true);
    expect(campaignService.canApproveTransition('validating', 'ready_for_approval')).toBe(true);
    expect(campaignService.canApproveTransition('ready_for_approval', 'approved')).toBe(true);
    expect(campaignService.canApproveTransition('approved', 'scheduled')).toBe(true);
    expect(campaignService.canApproveTransition('approved', 'cancelled')).toBe(true);
    expect(campaignService.canApproveTransition('rejected', 'pending')).toBe(false); // terminal
  });

  it('should validate execution transitions', () => {
    expect(campaignService.canExecuteTransition('pending', 'scheduled')).toBe(true);
    expect(campaignService.canExecuteTransition('scheduled', 'active')).toBe(true);
    expect(campaignService.canExecuteTransition('active', 'completed')).toBe(true);
    expect(campaignService.canExecuteTransition('active', 'paused')).toBe(true);
    expect(campaignService.canExecuteTransition('paused', 'active')).toBe(true);
    expect(campaignService.canExecuteTransition('completed', 'measured')).toBe(false); // terminal
  });
});